return {
    {
      'nvim-treesitter/nvim-treesitter',
      lazy = false,
      build = ':TSUpdate',
      config = function()
	require("nvim-treesitter.config").setup({
	    auto_install = true,
	    highlight = { enable = true },
	    indent = { enable = true },
      	    ensure_installed = {
      	        'bash',
      	        'c',
      	        'diff',
      	        'git_config',
      	        'git_rebase',
      	        'html',
      	        'ini',
      	        'javascript',
      	        'json',
      	        'lua',
      	        'luadoc',
      	        'luap',
      	        'make',
      	        'markdown',
      	        'markdown_inline',
      	        'powershell',
      	        'printf',
      	        'python',
      	        'query',
      	        'regex',
      	        'rust',
      	        'ssh_config',
      	        'toml',
      	        'typescript',
      	        'vim',
      	        'vimdoc',
      	        'xml',
      	        'yaml'
      	    },
      	})
	require'nvim-treesitter'.install { 
		'bash',
      	        'c',
      	        'diff',
      	        'git_config',
      	        'git_rebase',
      	        'html',
      	        'ini',
      	        'javascript',
      	        'json',
      	        'lua',
      	        'luadoc',
      	        'luap',
      	        'make',
      	        'markdown',
      	        'markdown_inline',
      	        'powershell',
      	        'printf',
      	        'python',
      	        'query',
      	        'regex',
      	        'rust',
      	        'ssh_config',
      	        'toml',
      	        'typescript',
      	        'vim',
      	        'vimdoc',
      	        'xml',
      	        'yaml'
	}
      end,
    }
}
